# version format
version: 1.0.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
  only:
    - master
platform:
  - x86
configuration: Release

before_build:
  - ps: Get-ChildItem Env:
  - cmd: nuget restore
  - cmd: ECHO MINGO this should also trigger a build